app = "number-change-portal-backend"
primary_region = "iad"  # Washington D.C. - you can change to "bom" for Mumbai, "sjc" for San Jose, etc.

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  NODE_ENV = "production"
  PORT = "3000"

